### ISSUE TITLE
Not able to use msgraph

### ISSUE THREAD

**Issue by lumayara** [alexziskind1/nativescript-msgraph#2]
Hi I tried putting this in my main.ts:

```
> import {SDKHelper} from "nativescript-msgraph";
> SDKHelper.Initialize(constantsModules.CLIENT_ID, constantsModules.ACTIVE_SCOPES);
```

but I keep getting this error:
node_modules/nativescript-msgraph/DriveRequestBuilder.d.ts(7,22): error TS2420: Class 'DriveRequestBuilder' incorrectly implements interface 'IDriveRequestBuilder'.
  Types of property 'Request' are incompatible.
    Type '(options?: Option[]) => IEntityRequest' is not assignable to type '(options?: Option[]) => IDriveRequest'.
      Type 'IEntityRequest' is not assignable to type 'IDriveRequest'.
        Types of property 'Create' are incompatible.
          Type '(entityToCreate: Entity, cancellationToken?: CancellationToken) => Promise<Entity>' is not assignable to type '(driveToCreate: Drive, cancellationToken?: CancellationToken) => Promise<Drive>'.
            Type 'Promise<Entity>' is not assignable to type 'Promise<Drive>'.
              Type 'Entity' is not assignable to type 'Drive'.
                Property 'DriveType' is missing in type 'Entity'.
11:18:56 AM - Compilation complete. Watching for file changes.

I was able to authenticate the user using oath, but now I need to send an email so I think I need msgraph. Has anyone had this problem? How to solve it? Thanks!

**Comment by alexziskind1** [comment]
The msgraph plugin hasn’t been updated for a while. After successfully authenticating, I suggest using the Graph API directly via http. 

Alex

**Comment by lumayara** [comment]
Thank you, Alex!
